---
- name: load variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install openjdk
  package:
    name: "{{ openjdk_jdk_package_name }}"
    state: installed
  tags:
    - openjdk_jdk_install_package
