---
- block:

    - name: load variables
      include_vars: "{{ ansible_os_family }}.yml"

    - name: install openjdk
      become: yes
      become_user: root
      package:
        name: "{{ openjdk_jdk_package_name }}"
        state: present
      tags:
        - openjdk_jdk_install_package

  tags:
    - openjdk
